### ISSUE TITLE
Possibility to run on OSX ?

### ISSUE THREAD

**Issue by BKaraargirov** [moby/libnetwork#2611]
Hi I was wondering whether it is possible to get this working on mac. Currently the issue I am facing is the lack of init script in ns, of course it could have others

**Comment by thaJeztah** [comment]
No, there's currently no code whatsoever that would work on macOS, and many of the code paths would likely be linux (or windows) specific

**Comment by claudobahn** [comment]
@thaJeztah is there a fork of this library for Mac somewhere, then? When using docker on Mac OSX, I'm getting error messages that match this library verbatim, see the issue I just filed: https://github.com/moby/libnetwork/issues/2614

Or is the code from this library pulled in for a Mac OSX build, but simply broken because it doesn't support Mac OSX?

**Comment by thaJeztah** [comment]
Docker Desktop runs linux containers, and uses a minimal VM that runs Linux. Libnetwork code is included in the docker daemon (https://github.com/moby/moby) as a build-time dependency

**Comment by akerouanton** [comment]
Thanks for asking.

As already answered in previous posts, libnetwork can't be run directly on macOS as it only supports Windows and Linux. MacOS is lacking important features that make it unsuitable for running containers without a VM.

This repo is now defunct, and not actively watched by maintainers, so let me close this issue.
